name            'h0tbird-ssh'
version         '0.0.1'
source          'https://github.com/h0tbird/puppet-ssh'
author          'Marc Villacorta'
license         'GPL'
summary         'SSH Module'
description     'Manages the SSH service.'
project_page    'https://github.com/h0tbird/puppet-ssh'
