name         'h0tbird-ssh'
version      '0.0.2'
author       'Marc Villacorta'
summary      'SSH Module'
description  'Manages the SSH service.'
license      'GPL'
project_page 'https://github.com/h0tbird/puppet-ssh'
source       'https://github.com/h0tbird/puppet-ssh'
dependency   'h0tbird/misclib', '>=0.0.1'
dependency   'puppetlabs/stdlib', '>=4.3.2'
